name: dart_test_signalr
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  http: ^1.2.1
  logging: ^1.2.0
  signalr_core: ^1.1.1
  web_socket_channel: ^2.4.5

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
